[package]
name = "nossochat_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
rand = "0.8.5"
reqwest = { version = "0.12", features = ["json", "blocking"] }
rsa = "0.9.8"
serde = "1.0.219"
serde_json = "1.0.142"
